<h1 class="text-center text-primary"><i class="bi bi-card-checklist"></i>Liste des menus <i class="bi bi-menu-up"></i> </h1>
        <h1> </h1>
        <div class="col">
         <a href="ajouterMenu.php" class="btn btn-success float-end"><i class="bi bi-plus-square"></i> Ajouter Menu </a>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    
                    <th scope="col">Title</th>
                    <th scope="col">Operations</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($menus as $menu) : ?>
                    <tr>
                        
                        <td><?= $menu['title'] ?></td>
                        <td>
                            <a href="menu_details.php?id=<?= $menu['idmenu']?>" class="btn btn-primary"><i class="bi bi-info-circle-fill"></i></a>
                            <a href="modifierMENU.php?id=<?= $menu['idmenu'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#suprimerMenu<?= $menu['idmenu'] ?>"><i class="bi bi-trash"></i></button>
                    <!-- Modal -->
                    <div class="modal fade" id="suprimerMenu<?= $menu['idmenu'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel"><?= $menu['title'] ?></h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Voulez-vous suprimer cette menu ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                                    <a href="suprimerMENU.php?id=<?= $menu['idmenu'] ?>" type="button" class="btn btn-danger">Suprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    