
<div class="container mb-4">
 
  <div id="myCarousel" class="carousel slide mb-4" data-ride="carousel" >
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="./assets/images/gallary_1.jpg" alt="Gallary" style="width:100%;">
      </div>

      <div class="item">
        <img src="./assets/images/gallary_2.jpg" alt="Gallary" style="width:100%;">
      </div>
    
      <div class="item">
        <img src="./assets/images/gallary_3.jpg" alt="Gallary" style="width:100%;">
      </div>
      <div class="item">
        <img src="./assets/images/gallary_4.jpg" alt="Gallary" style="width:100%;">
      </div>
      <div class="item">
        <img src="./assets/images/gallary_5.jpg" alt="Gallary" style="width:100%;">
      </div>
     

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" style="opacity:0"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" style="opacity:0"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!--About-->

  <div  id="about" class="mb-4">
        <div class="titre" ><h1 class="h1-responsive font-weight-bold text-center my-4" >A Propos de <span>Nous</span></h1></div>
         
        <div class="about mb-4">
        <div>
                <img src="./assets/images/Food-Plate.png" id="image">
            </div>

            <div class="about_text">
               
                <h3>Passionné</h3>
                <p>
                C’est officiel, nos portes sont est enfin ouvertes ! Passionné, c’est un nom que nous avons soigneusement choisi pour notre nouveau restaurant, dans le but de vous offrir une expérience riche en émotions, à la dégustation de chacun de nos plats. Retrouvez-nous au 17 Rue Bergère, dans le 9ème arrondissement de Paris, à quelques minutes du monument du Comptoir National d’Escompte de Paris.
Menée par le talentueux chef japonais Satoshi Horiuchi, cette nouvelle table gastronomique revisite avec panache et modernité la gastronomie française tout en respectant les petits producteurs et les saisons.
À l’honneur, une cuisine française gastronomique, soignée, haut de gamme et où l’on vous promet une explosion de saveurs à chaque bouchée; le tout dans un décor sophistiqué et moderne.
                </p>
            </div>
        </div>

        </div>

       

     

   <div class="gallary mb-4" id="menu">
      <div class="titre"> <h1 class="h1-responsive font-weight-bold text-center my-4">Nous<span>MENU</span></h1></div> 

        <div class="gallary_image_box row gx-3 gy-5">
         <?php foreach ($menus as $menu) : ?>
            <div class="gallary_image col-12 col-sm-6 col-md-4 col-lg-3 ">  
                <img class="image-menu rounded-top" src=" <?=$menu['image'] ?> ">

                <h3><?=$menu['title'] ?></h3>
                <p>
                <?=$menu['price']."<span><b>DT</b></span>" ?>
                </p>
                
            </div>

           <?php endforeach; ?>
       </div>
     </div>
     </div>
      <!--Section: Contact v.2-->
<section class="mb-4" id="contact">

<!--Section heading-->
<div class="titre"><h1 class="h1-responsive font-weight-bold text-center my-4">Contacter<span>Nous</span></h1></div>
<!--Section description-->
<p class="text-center w-responsive mx-auto mb-5">Avez-vous des questions? N'hésitez pas à nous contacter directement. Notre équipe reviendra vers vous dans les heures qui suivent pour vous aider.</p>

<div class="row">

    <!--Grid column-->
    <div class="col-md-9 mb-md-0 mb-5">
        <form id="contact-form" name="contact-form" action="mail.php" method="POST">

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-6">
                    <div class="md-form mb-0">
                        <input type="text" id="nom" name="nom" class="form-control">
                        <label for="nom" class="">Votre Nom</label>
                    </div>
                </div>
               

                <!--Grid column-->
                <div class="col-md-6">
                    <div class="md-form mb-0">
                        <input type="text" id="email" name="email" class="form-control">
                        <label for="email" class="">Votre email</label>
                    </div>
                </div>
                

            </div>
            

            <!--Grid row-->
            <div class="row">
                <div class="col-md-12">
                    <div class="md-form mb-0">
                        <input type="text" id="subject" name="sujet" class="form-control">
                        <label for="sujet" class="">Sujet</label>
                    </div>
                </div>
            </div>
           

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-12">

                    <div class="md-form">
                        <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                        <label for="message">Votre message</label>
                    </div>

                </div>
            </div>
            

        </form>

        <div class="text-center text-md-left">
            <a href="#" class="btn btn-primary" >Envoyer</a>
        </div>
        <div class="status"></div>
    </div>
    

    <!--Grid column-->
    <div class="col-md-3 text-center">
        <ul class="list-unstyled mb-0 text-success">
            <li><i class="bi bi-geo-alt-fill"></i> <p>Bousalem,Jendouba,Tunis</p> </li>

            <li><i class="bi bi-telephone-fill"></i><p>+216 29 611 488</p></li>

            <li><i class="bi bi-envelope-fill"></i><p>abidlifiras89@gmail.com</p></li>
        </ul>
    </div>
   

</div>

</section>
</div>


</body>
</html>