<link rel="stylesheet" href="./assets/css/login.css">
<main class="form-signin" >
    <?php if (count($errors) > 0) : ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <?= $errors[0] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php endif; ?>
    <form action="<?php $_SERVER['PHP_SELF'] ?>" method="post">
        <h1 class="h3 mb-3 fw-normal text-center text-light bg-primary rounded w-5 p-3">Login</h1>

        <div class="form-floating">
            <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit" name="submit">Se connecter</button>
        <br>
        <hr>
        <div class="text-center"><a href="signup.php" class="btn btn-success ">Creer nouveau compte</a></p>
        </div>
    </form>
</main>