
   
      <div class="row">
            <div class="col">
                <h3> Détails de <?=$menu['title'] ?> </h3>
            </div>

            <div class="col">
                <a href="GererMENU.php" class="btn btn-primary float-end"> <i class="bi bi-house-fill"></i>  </a>
            </div>
        </div> 

        <div class="card" style="width: 40rem;">
            
            <div class="card-body">
                <h5 class="card-title">Nom Menu</h5>
                <p class="card-text"><?=$menu['title'] ?></p>
                <hr>
                       <div class="card-text">
                            <p> <strong> prix </strong> </p>
                            <b> <?=$menu['price'] ?> DT </b>
                        </div>
            </div>
            <div class="card-body">
                <img src="<?=$menu['image'] ?>" alt="" class="img-fluid img-thumbnail" width=50%>
            </div>

            <div class="card-body">
            <a href="modifierMENU.php?id=<?= $menu['idmenu'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#suprimerMenu<?= $menu['idmenu'] ?>"><i class="bi bi-trash"></i></button>
                    <!-- Modal -->
                    <div class="modal fade" id="suprimerMenu<?= $menu['idmenu'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel"><?= $menu['title'] ?></h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Do you want to delete this Menu ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a href="suprimerMENU.php?id=<?= $menu['idmenu'] ?>" type="button" class="btn btn-danger">Suprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
        </div>
        
  
 