
   
      <div class="row">
            <div class="col">
                <h3> Détails de <?=$user['nom']." ".$user['prenom'] ?> </h3>
            </div>

            <div class="col">
                <a href="./GererUSERS.php" class="btn btn-primary float-end"> <i class="bi bi-house-fill"></i>  </a>
            </div>
        </div> 

        <div class="card" style="width: 40rem;">
            
         <ul class="list-group">
                
                <li class="list-group-item list-group-item-primary">Nom:<?=$user['nom'] ?></li>
                <li class="list-group-item list-group-item-primary">Prenom:<?=$user['prenom'] ?></li>
                <li class="list-group-item list-group-item-primary">Date de naissance:<?=$user['date_naissance'] ?></li>
                <li class="list-group-item list-group-item-primary">Numero de téléphone:<?=$user['tel'] ?></li>
                <li class="list-group-item list-group-item-primary">Adresse:<?=$user['adresse'] ?></li>
                <li class="list-group-item list-group-item-primary">Email:<?=$user['email'] ?></li>
                <li class="list-group-item list-group-item-primary">Password:<?=$user['password'] ?></li>
                <li class="list-group-item list-group-item-primary">Role:<?=$user['role'] ?></li>
                </ul>
            
            <div class="card-body">
                <img  src="<?=$user['avatar'] ?>" alt="" class="img-fluid rounded-circle" width=20% >
            </div>

            <div class="card-body" >
            <a href="modifierUser.php?id=<?= $user['id'] ?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#suprimerUser<?= $user['id'] ?>"><i class="bi bi-trash"></i></button>
                    <!-- Modal -->
                    <div class="modal fade" id="suprimerUser<?= $user['id'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel"><?= $user['nom']." ".$user['prenom'] ?></h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Do you want to delete this User ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a href="suprimerUser.php?id=<?= $user['id'] ?>" type="button" class="btn btn-danger">Suprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>       
        </div>
        </div>
        
  
 